"""Add order tracking, destination, and retail amount

Revision ID: 5e7f1e4949c0
Revises: a2bb06ce0c16
Create Date: 2026-06-09 22:46:16.241396
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '5e7f1e4949c0'
down_revision = 'a2bb06ce0c16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('sent_to_production_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('tracking_url', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('tracking_code', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('destination_city', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('destination_country', sa.String(length=128), nullable=True))
    op.add_column('orders', sa.Column('retail_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'retail_amount')
    op.drop_column('orders', 'destination_country')
    op.drop_column('orders', 'destination_city')
    op.drop_column('orders', 'tracking_code')
    op.drop_column('orders', 'tracking_url')
    op.drop_column('orders', 'sent_to_production_at')
    # ### end Alembic commands ###
