"""Add order and sync models

Revision ID: a2bb06ce0c16
Revises: 20260603_0006
Create Date: 2026-06-09 21:21:01.000212
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'a2bb06ce0c16'
down_revision = '20260603_0006'
branch_labels = None
depends_on = None


def _supports_constraint_alter() -> bool:
    return op.get_bind().dialect.name != "sqlite"


def _uses_postgresql_jsonb() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('provider_store_connection_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_order_id', sa.String(length=255), nullable=False),
    sa.Column('display_order_id', sa.String(length=255), nullable=False),
    sa.Column('marketplace_order_id', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('product_summary', sa.Text(), nullable=True),
    sa.Column('fulfillment_status', sa.String(length=64), nullable=False),
    sa.Column('production_status', sa.String(length=64), nullable=True),
    sa.Column('financial_status', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_order_url', sa.Text(), nullable=True),
    sa.Column('raw_payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'provider', 'external_order_id', name='uq_order_org_provider_external')
    )
    op.create_index(op.f('ix_orders_external_order_id'), 'orders', ['external_order_id'], unique=False)
    op.create_index('ix_orders_org_provider', 'orders', ['organization_id', 'provider'], unique=False)
    op.create_index(op.f('ix_orders_organization_id'), 'orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_orders_provider'), 'orders', ['provider'], unique=False)
    op.create_index(op.f('ix_orders_provider_store_connection_id'), 'orders', ['provider_store_connection_id'], unique=False)
    op.create_table('sync_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_jobs_org_type_status', 'sync_jobs', ['organization_id', 'job_type', 'status'], unique=False)
    op.create_index(op.f('ix_sync_jobs_organization_id'), 'sync_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sync_jobs_provider'), 'sync_jobs', ['provider'], unique=False)
    op.create_table('sync_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_job_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_store_connection_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sync_job_id'], ['sync_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_events_organization_id'), 'sync_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sync_events_provider'), 'sync_events', ['provider'], unique=False)
    op.create_index(op.f('ix_sync_events_provider_store_connection_id'), 'sync_events', ['provider_store_connection_id'], unique=False)
    op.create_index(op.f('ix_sync_events_sync_job_id'), 'sync_events', ['sync_job_id'], unique=False)
    if _supports_constraint_alter():
        op.drop_index('ix_organizations_join_code', table_name='organizations')
        op.create_unique_constraint(None, 'organizations', ['join_code'])
    if _uses_postgresql_jsonb():
        op.alter_column('pod_products', 'raw_provider_payload_json',
                   existing_type=postgresql.JSON(astext_type=sa.Text()),
                   type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
                   existing_nullable=True)
        op.alter_column('product_blueprints', 'placement_config_json',
                   existing_type=postgresql.JSON(astext_type=sa.Text()),
                   type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
                   existing_nullable=True)
        op.alter_column('product_blueprints', 'provider_snapshot_json',
                   existing_type=postgresql.JSON(astext_type=sa.Text()),
                   type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
                   existing_nullable=True)
        op.alter_column('product_blueprints', 'base_tags_json',
                   existing_type=postgresql.JSON(astext_type=sa.Text()),
                   type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
                   existing_nullable=True)
        op.alter_column('product_blueprints', 'basic_design_info_json',
                   existing_type=postgresql.JSON(astext_type=sa.Text()),
                   type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
                   existing_nullable=True)
        op.alter_column('provider_product_drafts', 'tags_json',
                   existing_type=postgresql.JSON(astext_type=sa.Text()),
                   type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
                   existing_nullable=True)
        op.alter_column('provider_store_connections', 'raw_data_json',
                   existing_type=postgresql.JSON(astext_type=sa.Text()),
                   type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
                   existing_nullable=True)
        op.alter_column('publishing_jobs', 'raw_result_json',
                   existing_type=postgresql.JSON(astext_type=sa.Text()),
                   type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _uses_postgresql_jsonb():
        op.alter_column('publishing_jobs', 'raw_result_json',
                   existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
                   type_=postgresql.JSON(astext_type=sa.Text()),
                   existing_nullable=True)
        op.alter_column('provider_store_connections', 'raw_data_json',
                   existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
                   type_=postgresql.JSON(astext_type=sa.Text()),
                   existing_nullable=True)
        op.alter_column('provider_product_drafts', 'tags_json',
                   existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
                   type_=postgresql.JSON(astext_type=sa.Text()),
                   existing_nullable=True)
        op.alter_column('product_blueprints', 'basic_design_info_json',
                   existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
                   type_=postgresql.JSON(astext_type=sa.Text()),
                   existing_nullable=True)
        op.alter_column('product_blueprints', 'base_tags_json',
                   existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
                   type_=postgresql.JSON(astext_type=sa.Text()),
                   existing_nullable=True)
        op.alter_column('product_blueprints', 'provider_snapshot_json',
                   existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
                   type_=postgresql.JSON(astext_type=sa.Text()),
                   existing_nullable=True)
        op.alter_column('product_blueprints', 'placement_config_json',
                   existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
                   type_=postgresql.JSON(astext_type=sa.Text()),
                   existing_nullable=True)
        op.alter_column('pod_products', 'raw_provider_payload_json',
                   existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
                   type_=postgresql.JSON(astext_type=sa.Text()),
                   existing_nullable=True)
    if _supports_constraint_alter():
        op.drop_constraint(None, 'organizations', type_='unique')
        op.create_index('ix_organizations_join_code', 'organizations', ['join_code'], unique=True)
    op.drop_index(op.f('ix_sync_events_sync_job_id'), table_name='sync_events')
    op.drop_index(op.f('ix_sync_events_provider_store_connection_id'), table_name='sync_events')
    op.drop_index(op.f('ix_sync_events_provider'), table_name='sync_events')
    op.drop_index(op.f('ix_sync_events_organization_id'), table_name='sync_events')
    op.drop_table('sync_events')
    op.drop_index(op.f('ix_sync_jobs_provider'), table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_organization_id'), table_name='sync_jobs')
    op.drop_index('ix_sync_jobs_org_type_status', table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_index(op.f('ix_orders_provider_store_connection_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_provider'), table_name='orders')
    op.drop_index(op.f('ix_orders_organization_id'), table_name='orders')
    op.drop_index('ix_orders_org_provider', table_name='orders')
    op.drop_index(op.f('ix_orders_external_order_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
